---
# ====== Application: Demo CSS HTML ==========================
identification: 
  name: Demo CSS HTML
  alias: DEMO-CSS-HTML
  version: Release 1.0

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 21.2 / 22.1 / 22.2
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 103093092090635281012

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_DEMOAPP007

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Demo CSS HTML

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu # 103093256648544281085
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 103093092873050281013

navigation-bar: 
  implementation: List
  list: Navigation Bar # 103093381612416281207
  list-template: Navigation Bar # 103093256250963281084
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Demo CSS HTML

component-settings: 
- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 103093088755823281009
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 15526539211221

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 103093089091828281010
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 15526539211228

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 103093089302794281010
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 15526539211237

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 103093089623047281010
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 15526539211237

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 103093089983043281011
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 15526539211239

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 103093090285398281011
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 15526539211242

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 103093090563640281011
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  settings: 
    attribute-1: Y

  subscription: 
    version-number: 15526539211247

- # ====== Component Setting: NATIVE_IR ========================
  id: 103093090872052281011
  identification: 
    name: NATIVE_IR
    type: Region

  settings: 
    attribute-1: IG

  subscription: 
    version-number: 15526539211250

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 103093091186470281011
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  settings: 
    attribute-1: Y

  subscription: 
    version-number: 15526539211255

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 103093091488228281011
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15526539211257

